project_id = "aabyxfcrrqivjupawxdu"

[auth]
site_url = "https://lokalshops.co.uk"
additional_redirect_urls = [
  "https://lokalshops.co.uk/auth/callback",
  "https://www.lokalshops.co.uk/auth/callback"
]

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[auth.email]
enable_confirmations = true
max_frequency = "1m0s"
otp_length = 8

[functions.send-review-alert]
verify_jwt = false

[functions.send-verification-alert]
verify_jwt = false

[functions.get-admin-verification-feed]
verify_jwt = false

[functions.process-verification-request]
verify_jwt = false