/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as RefundsCancellationsRouteImport } from './routes/refunds-cancellations'
import { Route as RateRouteImport } from './routes/rate'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OrderRouteImport } from './routes/order'
import { Route as MerchantRouteImport } from './routes/merchant'
import { Route as ListStoreRouteImport } from './routes/list-store'
import { Route as HelpRouteImport } from './routes/help'
import { Route as FollowingRouteImport } from './routes/following'
import { Route as FarmersMarketRouteImport } from './routes/farmers-market'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoreIdRouteImport } from './routes/store.$id'
import { Route as CustomerProfileRouteImport } from './routes/customer.profile'
import { Route as CustomerDashboardRouteImport } from './routes/customer.dashboard'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundsCancellationsRoute = RefundsCancellationsRouteImport.update({
  id: '/refunds-cancellations',
  path: '/refunds-cancellations',
  getParentRoute: () => rootRouteImport,
} as any)
const RateRoute = RateRouteImport.update({
  id: '/rate',
  path: '/rate',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderRoute = OrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantRoute = MerchantRouteImport.update({
  id: '/merchant',
  path: '/merchant',
  getParentRoute: () => rootRouteImport,
} as any)
const ListStoreRoute = ListStoreRouteImport.update({
  id: '/list-store',
  path: '/list-store',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowingRoute = FollowingRouteImport.update({
  id: '/following',
  path: '/following',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmersMarketRoute = FarmersMarketRouteImport.update({
  id: '/farmers-market',
  path: '/farmers-market',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreIdRoute = StoreIdRouteImport.update({
  id: '/store/$id',
  path: '/store/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerProfileRoute = CustomerProfileRouteImport.update({
  id: '/customer/profile',
  path: '/customer/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerDashboardRoute = CustomerDashboardRouteImport.update({
  id: '/customer/dashboard',
  path: '/customer/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRouteWithChildren
  '/booking': typeof BookingRoute
  '/farmers-market': typeof FarmersMarketRoute
  '/following': typeof FollowingRoute
  '/help': typeof HelpRoute
  '/list-store': typeof ListStoreRoute
  '/merchant': typeof MerchantRoute
  '/order': typeof OrderRoute
  '/privacy': typeof PrivacyRoute
  '/rate': typeof RateRoute
  '/refunds-cancellations': typeof RefundsCancellationsRoute
  '/terms': typeof TermsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/customer/dashboard': typeof CustomerDashboardRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/store/$id': typeof StoreIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRouteWithChildren
  '/booking': typeof BookingRoute
  '/farmers-market': typeof FarmersMarketRoute
  '/following': typeof FollowingRoute
  '/help': typeof HelpRoute
  '/list-store': typeof ListStoreRoute
  '/merchant': typeof MerchantRoute
  '/order': typeof OrderRoute
  '/privacy': typeof PrivacyRoute
  '/rate': typeof RateRoute
  '/refunds-cancellations': typeof RefundsCancellationsRoute
  '/terms': typeof TermsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/customer/dashboard': typeof CustomerDashboardRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/store/$id': typeof StoreIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRouteWithChildren
  '/booking': typeof BookingRoute
  '/farmers-market': typeof FarmersMarketRoute
  '/following': typeof FollowingRoute
  '/help': typeof HelpRoute
  '/list-store': typeof ListStoreRoute
  '/merchant': typeof MerchantRoute
  '/order': typeof OrderRoute
  '/privacy': typeof PrivacyRoute
  '/rate': typeof RateRoute
  '/refunds-cancellations': typeof RefundsCancellationsRoute
  '/terms': typeof TermsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/customer/dashboard': typeof CustomerDashboardRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/store/$id': typeof StoreIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/booking'
    | '/farmers-market'
    | '/following'
    | '/help'
    | '/list-store'
    | '/merchant'
    | '/order'
    | '/privacy'
    | '/rate'
    | '/refunds-cancellations'
    | '/terms'
    | '/auth/callback'
    | '/customer/dashboard'
    | '/customer/profile'
    | '/store/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/booking'
    | '/farmers-market'
    | '/following'
    | '/help'
    | '/list-store'
    | '/merchant'
    | '/order'
    | '/privacy'
    | '/rate'
    | '/refunds-cancellations'
    | '/terms'
    | '/auth/callback'
    | '/customer/dashboard'
    | '/customer/profile'
    | '/store/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/booking'
    | '/farmers-market'
    | '/following'
    | '/help'
    | '/list-store'
    | '/merchant'
    | '/order'
    | '/privacy'
    | '/rate'
    | '/refunds-cancellations'
    | '/terms'
    | '/auth/callback'
    | '/customer/dashboard'
    | '/customer/profile'
    | '/store/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRouteWithChildren
  BookingRoute: typeof BookingRoute
  FarmersMarketRoute: typeof FarmersMarketRoute
  FollowingRoute: typeof FollowingRoute
  HelpRoute: typeof HelpRoute
  ListStoreRoute: typeof ListStoreRoute
  MerchantRoute: typeof MerchantRoute
  OrderRoute: typeof OrderRoute
  PrivacyRoute: typeof PrivacyRoute
  RateRoute: typeof RateRoute
  RefundsCancellationsRoute: typeof RefundsCancellationsRoute
  TermsRoute: typeof TermsRoute
  CustomerDashboardRoute: typeof CustomerDashboardRoute
  CustomerProfileRoute: typeof CustomerProfileRoute
  StoreIdRoute: typeof StoreIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refunds-cancellations': {
      id: '/refunds-cancellations'
      path: '/refunds-cancellations'
      fullPath: '/refunds-cancellations'
      preLoaderRoute: typeof RefundsCancellationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rate': {
      id: '/rate'
      path: '/rate'
      fullPath: '/rate'
      preLoaderRoute: typeof RateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant': {
      id: '/merchant'
      path: '/merchant'
      fullPath: '/merchant'
      preLoaderRoute: typeof MerchantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list-store': {
      id: '/list-store'
      path: '/list-store'
      fullPath: '/list-store'
      preLoaderRoute: typeof ListStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/following': {
      id: '/following'
      path: '/following'
      fullPath: '/following'
      preLoaderRoute: typeof FollowingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmers-market': {
      id: '/farmers-market'
      path: '/farmers-market'
      fullPath: '/farmers-market'
      preLoaderRoute: typeof FarmersMarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/$id': {
      id: '/store/$id'
      path: '/store/$id'
      fullPath: '/store/$id'
      preLoaderRoute: typeof StoreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/profile': {
      id: '/customer/profile'
      path: '/customer/profile'
      fullPath: '/customer/profile'
      preLoaderRoute: typeof CustomerProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/dashboard': {
      id: '/customer/dashboard'
      path: '/customer/dashboard'
      fullPath: '/customer/dashboard'
      preLoaderRoute: typeof CustomerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRouteWithChildren,
  BookingRoute: BookingRoute,
  FarmersMarketRoute: FarmersMarketRoute,
  FollowingRoute: FollowingRoute,
  HelpRoute: HelpRoute,
  ListStoreRoute: ListStoreRoute,
  MerchantRoute: MerchantRoute,
  OrderRoute: OrderRoute,
  PrivacyRoute: PrivacyRoute,
  RateRoute: RateRoute,
  RefundsCancellationsRoute: RefundsCancellationsRoute,
  TermsRoute: TermsRoute,
  CustomerDashboardRoute: CustomerDashboardRoute,
  CustomerProfileRoute: CustomerProfileRoute,
  StoreIdRoute: StoreIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
